name: flutter_naulandarmawan_fundamental
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  hidden_drawer_menu: ^3.0.1
  lottie: ^2.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/images/
